import Task from '../models/Task.js';
import Agent from '../models/Agent.js';
import { logActivity } from './activityLogger.js';
import { logger } from '../config/logger.js';

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const generateMockOutput = (agentRole: string, taskTitle: string, taskDesc?: string): string => {
  const title = taskTitle.toLowerCase();
  const desc = (taskDesc || '').toLowerCase();

  if (
    agentRole.includes('Debug') ||
    agentRole.includes('Coder') ||
    title.includes('bug') ||
    title.includes('code') ||
    title.includes('fix') ||
    desc.includes('bug') ||
    desc.includes('code')
  ) {
    return `### AI Agent Code Review & Debug Execution
**Task Analyzed:** ${taskTitle}
**Target Issue:** ${taskDesc || 'No details provided.'}

#### 1. Root Cause Diagnosis
The code pattern indicates a potential concurrency race condition or an unhandled null exception during state serialization.

#### 2. Proposed Fix (Patch Diff)
\`\`\`javascript
const updateStateSafe = async (data) => {
  return await Db.withTransaction(async (session) => {
    const record = await Db.findByIdWithLock(data.id, {}, { session });
    if (!record) throw new Error('Record integrity violation');
    record.status = 'processed';
    return await record.save({ session });
  });
};
\`\`\`

#### 3. Resolution Verification
* Transaction boundaries locked successfully.
* Unit test passed: \`npm test -- suite/security-gate\` [SUCCESS]`;
  }

  if (
    agentRole.includes('Copy') ||
    agentRole.includes('Writer') ||
    title.includes('write') ||
    title.includes('email') ||
    title.includes('post') ||
    title.includes('content') ||
    desc.includes('write') ||
    desc.includes('content')
  ) {
    return `### AI Agent Copywriting Draft Output
**Task Objective:** ${taskTitle}
**Description Parameters:** ${taskDesc || 'No details provided.'}

---

#### 📢 Draft 1: High-Converting Headline Options
* Option A: "Say Goodbye to Digital Chaos: Meet *Advidus* Sentinel."
* Option B: "Enterprise Access Governance, Streamlined and Secured."

#### 📝 Draft 2: Product Introduction Section
"In today's fast-paced enterprise workspace, security vulnerabilities often stem from outdated access roles. Meet **_Advidus_ Sentinel**—the next-generation workspace orchestration portal that implements dynamic Permission-Based Access Control (PBAC), real-time session revocation guards, and lightweight BI analytics."

---
*Generated by AI Copywriting Agent*`;
  }

  return `### AI Agent Strategic Execution Plan
**Task:** ${taskTitle}
**Parameters:** ${taskDesc || 'No details provided.'}

#### 🎯 Strategic Analysis & Deliverables
1. **Core Problem Identification:** Isolated workflow processes causing task latency and security vulnerabilities in role assignments.
2. **Action Plan:**
   - **Step A:** Implement granular permission structures to isolate data assets.
   - **Step B:** Deploy a background task worker loop to handle asynchronous execution events.
3. **Execution Summary:** The task was successfully analyzed. The proposed workflows satisfy compliance matrices.

*AI Autopilot Execution Complete.*`;
};

export const executeAgentTask = async (taskId: string): Promise<void> => {
  try {
    const task = await Task.findById(taskId);
    if (!task) {
      logger.warn(`[AgentExecutor] Task not found: ${taskId}`);
      return;
    }

    if (task.assignedTo?.assigneeType !== 'agent' || !task.assignedTo.agent) {
      return;
    }

    const agent = await Agent.findById(task.assignedTo.agent);
    if (!agent) {
      logger.warn(`[AgentExecutor] AI Agent not found for task: ${taskId}`);
      return;
    }

    if (agent.status === 'inactive') {
      task.executionLogs = [
        {
          timestamp: new Date(),
          step: 'Execution Blocked',
          description: `Agent "${agent.name}" is deactivated. Reactivate to rerun.`,
          status: 'error',
        },
      ];
      await task.save();
      return;
    }

    logger.info(`[AgentExecutor] Running task "${task.title}" with agent "${agent.name}"`);

    task.status = 'in_progress';
    task.executionLogs = [
      {
        timestamp: new Date(),
        step: 'Agent Initialized',
        description: `Agent "${agent.name}" (${agent.role}) spawned. System prompt loaded.`,
        status: 'info',
      },
    ];
    await task.save();
    await sleep(1500);

    task.executionLogs.push({
      timestamp: new Date(),
      step: 'Payload Analysis',
      description: `Task specs parsed. Title: "${task.title}". Model: ${agent.modelName}.`,
      status: 'info',
    });
    await task.save();
    await sleep(1500);

    task.executionLogs.push({
      timestamp: new Date(),
      step: 'Reasoning Engine',
      description: 'Analyzing and executing generation steps.',
      status: 'info',
    });
    await task.save();
    await sleep(1500);

    const agentOutput = generateMockOutput(agent.role, task.title, task.description);

    task.status = 'completed';
    task.result = agentOutput;
    task.executionLogs.push({
      timestamp: new Date(),
      step: 'Task Completed',
      description: 'Final result compiled and validated.',
      status: 'success',
    });
    await task.save();

    await logActivity(
      task.owner.toString(),
      'TASK_UPDATED',
      `AI Agent "${agent.name}" completed task: "${task.title}"`
    );

    logger.info(`[AgentExecutor] Task "${task.title}" completed by "${agent.name}"`);
  } catch (error) {
    logger.error(`[AgentExecutor] Error on task ${taskId}:`, { error });
    try {
      const task = await Task.findById(taskId);
      if (task) {
        task.status = 'pending';
        task.executionLogs.push({
          timestamp: new Date(),
          step: 'Execution Failed',
          description: `Critical error: ${error instanceof Error ? error.message : 'Unknown error'}`,
          status: 'error',
        });
        await task.save();
      }
    } catch (e) {
      logger.error('[AgentExecutor] Failed to write error log:', { error: e });
    }
  }
};
